In [1]:
import gymnasium as gym
# import Lorenz_envs
import matplotlib.pyplot as plt
import numpy as np
import time
import torch
import warnings
import copy 
import wandb
import le_envs

from IPython import display
from torch.distributions import MultivariateNormal
from torch.optim import Adam
from torch.nn import Linear, Module, MSELoss, ReLU, Sequential

In [2]:
from le_envs.wrappers.VectorResetWrapper import VectorResetWrapper

In [3]:
envs = gym.make_vec("le_envs/Lorenz-v0", num_envs=3)

In [4]:
s = envs.reset(seed=42)

In [5]:
wrap = VectorResetWrapper(envs)

In [8]:
wrap.reset()

(array([[ 32.24378294, -10.10588475,  34.67343771],
        [ 32.24389353, -10.10509151,  34.67506917],
        [ 32.24374606, -10.10464032,  34.67323772]]),
 {})

In [29]:
s = envs.reset(seed=42)

In [30]:
np.full((3, 5), 7)

(array([[ 23.328024 ,  -4.0062127,  59.592354 ],
        [-14.649049 , -34.02899  ,  50.223568 ],
        [ -4.4378686, -13.016587 ,   9.42877  ]], dtype=float32),
 {})

In [19]:
envs.action_space

Box(-2.0, 2.0, (3, 3), float32)

In [20]:
actions = np.array([[1,1,1], [0,1,1], [1,1,1]])
observations, rewards, termination, truncation, infos = envs.step(actions)

In [21]:
observations

array([[ 20.646122 , -10.347049 ,  56.69563  ],
       [-16.291643 , -29.706339 ,  54.035065 ],
       [ -5.0390987, -13.499615 ,  10.047585 ]], dtype=float32)

In [22]:
rewards

array([1, 1, 1])

In [23]:
termination

array([False, False, False])